### ISSUE TITLE
Patched

### ISSUE THREAD

**Issue by KeevoDev** [Mouad-scriptz/Discord-Account-CreatorPY#2]
all tokens generated are locked.
https://i.imgur.com/PsZXbfo.png

**Comment by Mouad-scriptz** [comment]
what captcha provider are you using?

**Comment by KeevoDev** [comment]
> what captcha provider are you using?

i tried the both capmonster and capsolver with rotating proxies

**Comment by Mouad-scriptz** [comment]
try singapore iproyal proxies with high end enabled
